// 250+ ta keng tarqalgan inglizcha so'z. Toifalar bo'yicha guruhlangan.
// seed.ts dan chaqiriladi. Ingliz tili (en) uchun.

export const COMMON_WORDS = [
  // ─── Salomlashish va vejlivlik (A1) ───
  { text: 'hello',      translation: 'salom',          category: "Salomlashish", level: 'A1' },
  { text: 'hi',         translation: 'salom',          category: "Salomlashish", level: 'A1' },
  { text: 'goodbye',    translation: 'xayr',           category: "Salomlashish", level: 'A1' },
  { text: 'bye',        translation: 'xayr',           category: "Salomlashish", level: 'A1' },
  { text: 'good morning', translation: 'xayrli tong',  category: "Salomlashish", level: 'A1' },
  { text: 'good evening', translation: 'xayrli kech',  category: "Salomlashish", level: 'A1' },
  { text: 'good night',   translation: 'xayrli tun',   category: "Salomlashish", level: 'A1' },
  { text: 'thank you',  translation: 'rahmat',         category: "Salomlashish", level: 'A1' },
  { text: 'please',     translation: 'iltimos',        category: "Salomlashish", level: 'A1' },
  { text: 'sorry',      translation: 'kechirasiz',     category: "Salomlashish", level: 'A1' },
  { text: 'yes',        translation: 'ha',             category: "Salomlashish", level: 'A1' },
  { text: 'no',         translation: "yo'q",           category: "Salomlashish", level: 'A1' },

  // ─── Oila ───
  { text: 'family',     translation: 'oila',           category: 'Oila', level: 'A1' },
  { text: 'mother',     translation: 'ona',            category: 'Oila', level: 'A1' },
  { text: 'father',     translation: 'ota',            category: 'Oila', level: 'A1' },
  { text: 'son',        translation: "o'g'il",         category: 'Oila', level: 'A1' },
  { text: 'daughter',   translation: 'qiz',            category: 'Oila', level: 'A1' },
  { text: 'brother',    translation: 'aka/uka',        category: 'Oila', level: 'A1' },
  { text: 'sister',     translation: 'opa/singil',     category: 'Oila', level: 'A1' },
  { text: 'grandfather', translation: 'bobo',          category: 'Oila', level: 'A1' },
  { text: 'grandmother', translation: 'buvi',          category: 'Oila', level: 'A1' },
  { text: 'husband',    translation: 'er',             category: 'Oila', level: 'A2' },
  { text: 'wife',       translation: 'xotin',          category: 'Oila', level: 'A2' },
  { text: 'child',      translation: 'bola',           category: 'Oila', level: 'A1' },
  { text: 'baby',       translation: 'chaqaloq',       category: 'Oila', level: 'A2' },
  { text: 'uncle',      translation: 'tog\'a/amaki',   category: 'Oila', level: 'A2' },
  { text: 'aunt',       translation: 'xola/amma',      category: 'Oila', level: 'A2' },

  // ─── Sonlar ───
  { text: 'one',        translation: 'bir',            category: 'Sonlar', level: 'A1' },
  { text: 'two',        translation: 'ikki',           category: 'Sonlar', level: 'A1' },
  { text: 'three',      translation: 'uch',            category: 'Sonlar', level: 'A1' },
  { text: 'four',       translation: "to'rt",          category: 'Sonlar', level: 'A1' },
  { text: 'five',       translation: 'besh',           category: 'Sonlar', level: 'A1' },
  { text: 'six',        translation: 'olti',           category: 'Sonlar', level: 'A1' },
  { text: 'seven',      translation: 'yetti',          category: 'Sonlar', level: 'A1' },
  { text: 'eight',      translation: 'sakkiz',         category: 'Sonlar', level: 'A1' },
  { text: 'nine',       translation: "to'qqiz",        category: 'Sonlar', level: 'A1' },
  { text: 'ten',        translation: "o'n",            category: 'Sonlar', level: 'A1' },
  { text: 'twenty',     translation: 'yigirma',        category: 'Sonlar', level: 'A1' },
  { text: 'thirty',     translation: 'o\'ttiz',        category: 'Sonlar', level: 'A1' },
  { text: 'fifty',      translation: 'ellik',          category: 'Sonlar', level: 'A1' },
  { text: 'hundred',    translation: 'yuz',            category: 'Sonlar', level: 'A1' },
  { text: 'thousand',   translation: 'ming',           category: 'Sonlar', level: 'A2' },
  { text: 'million',    translation: 'million',        category: 'Sonlar', level: 'A2' },

  // ─── Ranglar ───
  { text: 'red',        translation: 'qizil',          category: 'Ranglar', level: 'A1' },
  { text: 'blue',       translation: "ko'k",           category: 'Ranglar', level: 'A1' },
  { text: 'green',      translation: 'yashil',         category: 'Ranglar', level: 'A1' },
  { text: 'yellow',     translation: 'sariq',          category: 'Ranglar', level: 'A1' },
  { text: 'black',      translation: 'qora',           category: 'Ranglar', level: 'A1' },
  { text: 'white',      translation: 'oq',             category: 'Ranglar', level: 'A1' },
  { text: 'orange',     translation: 'apelsin rangi',  category: 'Ranglar', level: 'A2' },
  { text: 'pink',       translation: 'pushti',         category: 'Ranglar', level: 'A2' },
  { text: 'purple',     translation: 'binafsha',       category: 'Ranglar', level: 'A2' },
  { text: 'brown',      translation: 'jigarrang',      category: 'Ranglar', level: 'A2' },
  { text: 'grey',       translation: 'kulrang',        category: 'Ranglar', level: 'A2' },

  // ─── Ovqat va ichimliklar ───
  { text: 'water',      translation: 'suv',            category: 'Ovqat', level: 'A1' },
  { text: 'bread',      translation: 'non',            category: 'Ovqat', level: 'A1' },
  { text: 'meat',       translation: "go'sht",         category: 'Ovqat', level: 'A1' },
  { text: 'milk',       translation: 'sut',            category: 'Ovqat', level: 'A1' },
  { text: 'tea',        translation: 'choy',           category: 'Ovqat', level: 'A1' },
  { text: 'coffee',     translation: 'qahva',          category: 'Ovqat', level: 'A1' },
  { text: 'sugar',      translation: 'shakar',         category: 'Ovqat', level: 'A1' },
  { text: 'salt',       translation: 'tuz',            category: 'Ovqat', level: 'A1' },
  { text: 'rice',       translation: 'guruch',         category: 'Ovqat', level: 'A1' },
  { text: 'apple',      translation: 'olma',           category: 'Ovqat', level: 'A1' },
  { text: 'banana',     translation: 'banan',          category: 'Ovqat', level: 'A1' },
  { text: 'orange',     translation: 'apelsin',        category: 'Ovqat', level: 'A1' },
  { text: 'grape',      translation: 'uzum',           category: 'Ovqat', level: 'A2' },
  { text: 'watermelon', translation: 'tarvuz',         category: 'Ovqat', level: 'A2' },
  { text: 'melon',      translation: 'qovun',          category: 'Ovqat', level: 'A2' },
  { text: 'tomato',     translation: 'pomidor',        category: 'Ovqat', level: 'A1' },
  { text: 'potato',     translation: 'kartoshka',      category: 'Ovqat', level: 'A1' },
  { text: 'onion',      translation: 'piyoz',          category: 'Ovqat', level: 'A1' },
  { text: 'carrot',     translation: 'sabzi',          category: 'Ovqat', level: 'A1' },
  { text: 'chicken',    translation: 'tovuq',          category: 'Ovqat', level: 'A1' },
  { text: 'fish',       translation: 'baliq',          category: 'Ovqat', level: 'A1' },
  { text: 'egg',        translation: 'tuxum',          category: 'Ovqat', level: 'A1' },
  { text: 'cheese',     translation: 'pishloq',        category: 'Ovqat', level: 'A2' },
  { text: 'butter',     translation: 'sariyog\'',      category: 'Ovqat', level: 'A2' },
  { text: 'breakfast',  translation: 'nonushta',       category: 'Ovqat', level: 'A2' },
  { text: 'lunch',      translation: 'tushlik',        category: 'Ovqat', level: 'A2' },
  { text: 'dinner',     translation: 'kechki ovqat',   category: 'Ovqat', level: 'A2' },
  { text: 'food',       translation: 'ovqat',          category: 'Ovqat', level: 'A1' },

  // ─── Kunlar / vaqt ───
  { text: 'today',      translation: 'bugun',          category: 'Vaqt', level: 'A1' },
  { text: 'tomorrow',   translation: 'ertaga',         category: 'Vaqt', level: 'A1' },
  { text: 'yesterday',  translation: 'kecha',          category: 'Vaqt', level: 'A1' },
  { text: 'now',        translation: 'hozir',          category: 'Vaqt', level: 'A1' },
  { text: 'later',      translation: 'keyinroq',       category: 'Vaqt', level: 'A2' },
  { text: 'morning',    translation: 'ertalab',        category: 'Vaqt', level: 'A1' },
  { text: 'afternoon',  translation: 'tushdan keyin',  category: 'Vaqt', level: 'A2' },
  { text: 'evening',    translation: 'kechqurun',      category: 'Vaqt', level: 'A1' },
  { text: 'night',      translation: 'tun',            category: 'Vaqt', level: 'A1' },
  { text: 'day',        translation: 'kun',            category: 'Vaqt', level: 'A1' },
  { text: 'week',       translation: 'hafta',          category: 'Vaqt', level: 'A1' },
  { text: 'month',      translation: 'oy',             category: 'Vaqt', level: 'A1' },
  { text: 'year',       translation: 'yil',            category: 'Vaqt', level: 'A1' },
  { text: 'hour',       translation: 'soat',           category: 'Vaqt', level: 'A1' },
  { text: 'minute',     translation: 'daqiqa',         category: 'Vaqt', level: 'A2' },
  { text: 'second',     translation: 'soniya',         category: 'Vaqt', level: 'A2' },
  { text: 'Monday',     translation: 'dushanba',       category: 'Vaqt', level: 'A1' },
  { text: 'Tuesday',    translation: 'seshanba',       category: 'Vaqt', level: 'A1' },
  { text: 'Wednesday',  translation: 'chorshanba',     category: 'Vaqt', level: 'A1' },
  { text: 'Thursday',   translation: 'payshanba',      category: 'Vaqt', level: 'A1' },
  { text: 'Friday',     translation: 'juma',           category: 'Vaqt', level: 'A1' },
  { text: 'Saturday',   translation: 'shanba',         category: 'Vaqt', level: 'A1' },
  { text: 'Sunday',     translation: 'yakshanba',      category: 'Vaqt', level: 'A1' },

  // ─── Tana qismlari ───
  { text: 'head',       translation: 'bosh',           category: 'Tana', level: 'A1' },
  { text: 'eye',        translation: "ko'z",           category: 'Tana', level: 'A1' },
  { text: 'ear',        translation: 'quloq',          category: 'Tana', level: 'A1' },
  { text: 'nose',       translation: 'burun',          category: 'Tana', level: 'A1' },
  { text: 'mouth',      translation: 'og\'iz',         category: 'Tana', level: 'A1' },
  { text: 'hand',       translation: 'qo\'l',          category: 'Tana', level: 'A1' },
  { text: 'foot',       translation: 'oyoq',           category: 'Tana', level: 'A1' },
  { text: 'heart',      translation: 'yurak',          category: 'Tana', level: 'A1' },
  { text: 'hair',       translation: 'soch',           category: 'Tana', level: 'A1' },
  { text: 'face',       translation: 'yuz',            category: 'Tana', level: 'A1' },
  { text: 'tooth',      translation: 'tish',           category: 'Tana', level: 'A2' },
  { text: 'finger',     translation: 'barmoq',         category: 'Tana', level: 'A2' },
  { text: 'leg',        translation: 'oyoq',           category: 'Tana', level: 'A1' },
  { text: 'arm',        translation: 'qo\'l',          category: 'Tana', level: 'A1' },
  { text: 'back',       translation: 'orqa',           category: 'Tana', level: 'A2' },

  // ─── Hayvonlar ───
  { text: 'dog',        translation: 'it',             category: 'Hayvonlar', level: 'A1' },
  { text: 'cat',        translation: 'mushuk',         category: 'Hayvonlar', level: 'A1' },
  { text: 'horse',      translation: 'ot',             category: 'Hayvonlar', level: 'A1' },
  { text: 'cow',        translation: 'sigir',          category: 'Hayvonlar', level: 'A1' },
  { text: 'sheep',      translation: "qo'y",           category: 'Hayvonlar', level: 'A2' },
  { text: 'bird',       translation: 'qush',           category: 'Hayvonlar', level: 'A1' },
  { text: 'fish',       translation: 'baliq',          category: 'Hayvonlar', level: 'A1' },
  { text: 'lion',       translation: 'sher',           category: 'Hayvonlar', level: 'A2' },
  { text: 'tiger',      translation: 'yo\'lbars',      category: 'Hayvonlar', level: 'A2' },
  { text: 'elephant',   translation: 'fil',            category: 'Hayvonlar', level: 'A2' },
  { text: 'monkey',     translation: 'maymun',         category: 'Hayvonlar', level: 'A2' },
  { text: 'rabbit',     translation: 'quyon',          category: 'Hayvonlar', level: 'A2' },
  { text: 'mouse',      translation: 'sichqon',        category: 'Hayvonlar', level: 'A2' },
  { text: 'snake',      translation: 'ilon',           category: 'Hayvonlar', level: 'A2' },
  { text: 'bear',       translation: 'ayiq',           category: 'Hayvonlar', level: 'A2' },

  // ─── Uy / mebel ───
  { text: 'house',      translation: 'uy',             category: 'Uy', level: 'A1' },
  { text: 'room',       translation: 'xona',           category: 'Uy', level: 'A1' },
  { text: 'door',       translation: 'eshik',          category: 'Uy', level: 'A1' },
  { text: 'window',     translation: 'deraza',         category: 'Uy', level: 'A1' },
  { text: 'table',      translation: 'stol',           category: 'Uy', level: 'A1' },
  { text: 'chair',      translation: "o'rindiq",       category: 'Uy', level: 'A1' },
  { text: 'bed',        translation: 'krovat',         category: 'Uy', level: 'A1' },
  { text: 'kitchen',    translation: 'oshxona',        category: 'Uy', level: 'A1' },
  { text: 'bathroom',   translation: 'hammom',         category: 'Uy', level: 'A2' },
  { text: 'bedroom',    translation: 'yotoqxona',      category: 'Uy', level: 'A2' },
  { text: 'living room', translation: 'mehmonxona',    category: 'Uy', level: 'A2' },
  { text: 'wall',       translation: 'devor',          category: 'Uy', level: 'A2' },
  { text: 'floor',      translation: 'pol',            category: 'Uy', level: 'A2' },
  { text: 'roof',       translation: 'tom',            category: 'Uy', level: 'A2' },

  // ─── Kasblar ───
  { text: 'teacher',    translation: "o'qituvchi",     category: 'Kasblar', level: 'A1' },
  { text: 'student',    translation: 'talaba',         category: 'Kasblar', level: 'A1' },
  { text: 'doctor',     translation: 'shifokor',       category: 'Kasblar', level: 'A1' },
  { text: 'nurse',      translation: 'hamshira',       category: 'Kasblar', level: 'A2' },
  { text: 'engineer',   translation: 'muhandis',       category: 'Kasblar', level: 'A2' },
  { text: 'driver',     translation: 'haydovchi',      category: 'Kasblar', level: 'A2' },
  { text: 'lawyer',     translation: 'advokat',        category: 'Kasblar', level: 'B1' },
  { text: 'cook',       translation: 'oshpaz',         category: 'Kasblar', level: 'A2' },
  { text: 'farmer',     translation: 'fermer',         category: 'Kasblar', level: 'A2' },
  { text: 'pilot',      translation: 'uchuvchi',       category: 'Kasblar', level: 'B1' },
  { text: 'soldier',    translation: 'askar',          category: 'Kasblar', level: 'B1' },
  { text: 'artist',     translation: 'rassom',         category: 'Kasblar', level: 'B1' },

  // ─── Joylar ───
  { text: 'city',       translation: 'shahar',         category: 'Joylar', level: 'A1' },
  { text: 'country',    translation: 'mamlakat',       category: 'Joylar', level: 'A1' },
  { text: 'village',    translation: 'qishloq',        category: 'Joylar', level: 'A2' },
  { text: 'street',     translation: "ko'cha",         category: 'Joylar', level: 'A1' },
  { text: 'school',     translation: 'maktab',         category: 'Joylar', level: 'A1' },
  { text: 'hospital',   translation: 'kasalxona',      category: 'Joylar', level: 'A1' },
  { text: 'market',     translation: 'bozor',          category: 'Joylar', level: 'A1' },
  { text: 'shop',       translation: "do'kon",         category: 'Joylar', level: 'A1' },
  { text: 'restaurant', translation: 'restoran',       category: 'Joylar', level: 'A1' },
  { text: 'park',       translation: 'bog\'',          category: 'Joylar', level: 'A1' },
  { text: 'airport',    translation: 'aeroport',       category: 'Joylar', level: 'A2' },
  { text: 'station',    translation: 'bekat',          category: 'Joylar', level: 'A2' },
  { text: 'church',     translation: 'cherkov',        category: 'Joylar', level: 'B1' },
  { text: 'mosque',     translation: 'masjid',         category: 'Joylar', level: 'A2' },
  { text: 'museum',     translation: 'muzey',          category: 'Joylar', level: 'A2' },
  { text: 'library',    translation: 'kutubxona',      category: 'Joylar', level: 'A2' },
  { text: 'office',     translation: 'ofis',           category: 'Joylar', level: 'A1' },
  { text: 'bank',       translation: 'bank',           category: 'Joylar', level: 'A1' },

  // ─── Tabiat ───
  { text: 'sun',        translation: 'quyosh',         category: 'Tabiat', level: 'A1' },
  { text: 'moon',       translation: 'oy',             category: 'Tabiat', level: 'A1' },
  { text: 'star',       translation: 'yulduz',         category: 'Tabiat', level: 'A1' },
  { text: 'sky',        translation: 'osmon',          category: 'Tabiat', level: 'A1' },
  { text: 'cloud',      translation: 'bulut',          category: 'Tabiat', level: 'A2' },
  { text: 'rain',       translation: 'yomg\'ir',       category: 'Tabiat', level: 'A1' },
  { text: 'snow',       translation: 'qor',            category: 'Tabiat', level: 'A1' },
  { text: 'wind',       translation: 'shamol',         category: 'Tabiat', level: 'A2' },
  { text: 'tree',       translation: 'daraxt',         category: 'Tabiat', level: 'A1' },
  { text: 'flower',     translation: 'gul',            category: 'Tabiat', level: 'A1' },
  { text: 'leaf',       translation: 'barg',           category: 'Tabiat', level: 'A2' },
  { text: 'grass',      translation: "o't",            category: 'Tabiat', level: 'A2' },
  { text: 'mountain',   translation: 'tog\'',          category: 'Tabiat', level: 'A1' },
  { text: 'river',      translation: 'daryo',          category: 'Tabiat', level: 'A2' },
  { text: 'sea',        translation: 'dengiz',         category: 'Tabiat', level: 'A2' },
  { text: 'forest',     translation: "o'rmon",         category: 'Tabiat', level: 'A2' },
  { text: 'fire',       translation: 'olov',           category: 'Tabiat', level: 'A2' },
  { text: 'earth',      translation: 'yer',            category: 'Tabiat', level: 'A2' },
  { text: 'world',      translation: 'dunyo',          category: 'Tabiat', level: 'A1' },

  // ─── Fe'llar (eng kerakli) ───
  { text: 'be',         translation: "bo'lmoq",         category: "Fe'llar", level: 'A1' },
  { text: 'have',       translation: 'ega bo\'lmoq',    category: "Fe'llar", level: 'A1' },
  { text: 'do',         translation: 'qilmoq',          category: "Fe'llar", level: 'A1' },
  { text: 'go',         translation: 'bormoq',          category: "Fe'llar", level: 'A1' },
  { text: 'come',       translation: 'kelmoq',          category: "Fe'llar", level: 'A1' },
  { text: 'see',        translation: "ko'rmoq",         category: "Fe'llar", level: 'A1' },
  { text: 'eat',        translation: 'yemoq',           category: "Fe'llar", level: 'A1' },
  { text: 'drink',      translation: 'ichmoq',          category: "Fe'llar", level: 'A1' },
  { text: 'sleep',      translation: 'uxlamoq',         category: "Fe'llar", level: 'A1' },
  { text: 'walk',       translation: 'yurmoq',          category: "Fe'llar", level: 'A1' },
  { text: 'run',        translation: 'yugurmoq',        category: "Fe'llar", level: 'A1' },
  { text: 'read',       translation: "o'qimoq",         category: "Fe'llar", level: 'A1' },
  { text: 'write',      translation: 'yozmoq',          category: "Fe'llar", level: 'A1' },
  { text: 'speak',      translation: 'gapirmoq',        category: "Fe'llar", level: 'A1' },
  { text: 'listen',     translation: 'tinglamoq',       category: "Fe'llar", level: 'A1' },
  { text: 'work',       translation: 'ishlamoq',        category: "Fe'llar", level: 'A1' },
  { text: 'study',      translation: "o'qimoq",         category: "Fe'llar", level: 'A1' },
  { text: 'learn',      translation: "o'rganmoq",       category: "Fe'llar", level: 'A1' },
  { text: 'understand', translation: 'tushunmoq',       category: "Fe'llar", level: 'A2' },
  { text: 'know',       translation: 'bilmoq',          category: "Fe'llar", level: 'A1' },
  { text: 'think',      translation: "o'ylash",         category: "Fe'llar", level: 'A1' },
  { text: 'want',       translation: 'istamoq',         category: "Fe'llar", level: 'A1' },
  { text: 'need',       translation: 'kerak',           category: "Fe'llar", level: 'A1' },
  { text: 'like',       translation: 'yoqtirmoq',       category: "Fe'llar", level: 'A1' },
  { text: 'love',       translation: 'sevmoq',          category: "Fe'llar", level: 'A1' },
  { text: 'help',       translation: 'yordam bermoq',   category: "Fe'llar", level: 'A1' },
  { text: 'open',       translation: 'ochmoq',          category: "Fe'llar", level: 'A1' },
  { text: 'close',      translation: 'yopmoq',          category: "Fe'llar", level: 'A1' },
  { text: 'buy',        translation: 'sotib olmoq',     category: "Fe'llar", level: 'A1' },
  { text: 'sell',       translation: 'sotmoq',          category: "Fe'llar", level: 'A2' },
  { text: 'give',       translation: 'bermoq',          category: "Fe'llar", level: 'A1' },
  { text: 'take',       translation: 'olmoq',           category: "Fe'llar", level: 'A1' },
  { text: 'sing',       translation: 'qo\'shiq aytmoq', category: "Fe'llar", level: 'A2' },
  { text: 'dance',      translation: 'raqsga tushmoq',  category: "Fe'llar", level: 'A2' },
  { text: 'play',       translation: "o'ynamoq",        category: "Fe'llar", level: 'A1' },
  { text: 'win',        translation: 'g\'alaba qozonmoq', category: "Fe'llar", level: 'A2' },
  { text: 'lose',       translation: 'yutqazmoq',       category: "Fe'llar", level: 'A2' },
  { text: 'start',      translation: 'boshlamoq',       category: "Fe'llar", level: 'A2' },
  { text: 'stop',       translation: "to'xtamoq",       category: "Fe'llar", level: 'A2' },
  { text: 'finish',     translation: 'tugatmoq',        category: "Fe'llar", level: 'A2' },

  // ─── Sifatlar ───
  { text: 'big',        translation: 'katta',           category: 'Sifatlar', level: 'A1' },
  { text: 'small',      translation: 'kichik',          category: 'Sifatlar', level: 'A1' },
  { text: 'good',       translation: 'yaxshi',          category: 'Sifatlar', level: 'A1' },
  { text: 'bad',        translation: 'yomon',           category: 'Sifatlar', level: 'A1' },
  { text: 'new',        translation: 'yangi',           category: 'Sifatlar', level: 'A1' },
  { text: 'old',        translation: 'eski',            category: 'Sifatlar', level: 'A1' },
  { text: 'young',      translation: 'yosh',            category: 'Sifatlar', level: 'A1' },
  { text: 'hot',        translation: 'issiq',           category: 'Sifatlar', level: 'A1' },
  { text: 'cold',       translation: 'sovuq',           category: 'Sifatlar', level: 'A1' },
  { text: 'warm',       translation: 'iliq',            category: 'Sifatlar', level: 'A2' },
  { text: 'fast',       translation: 'tez',             category: 'Sifatlar', level: 'A1' },
  { text: 'slow',       translation: 'sekin',           category: 'Sifatlar', level: 'A1' },
  { text: 'easy',       translation: 'oson',            category: 'Sifatlar', level: 'A1' },
  { text: 'hard',       translation: 'qiyin',           category: 'Sifatlar', level: 'A1' },
  { text: 'happy',      translation: 'baxtli',          category: 'Sifatlar', level: 'A1' },
  { text: 'sad',        translation: 'g\'amgin',        category: 'Sifatlar', level: 'A1' },
  { text: 'beautiful',  translation: 'chiroyli',        category: 'Sifatlar', level: 'A1' },
  { text: 'ugly',       translation: 'xunuk',           category: 'Sifatlar', level: 'A2' },
  { text: 'rich',       translation: 'boy',             category: 'Sifatlar', level: 'A2' },
  { text: 'poor',       translation: 'kambag\'al',      category: 'Sifatlar', level: 'A2' },
  { text: 'strong',     translation: 'kuchli',          category: 'Sifatlar', level: 'A2' },
  { text: 'weak',       translation: 'zaif',            category: 'Sifatlar', level: 'A2' },
  { text: 'tall',       translation: 'baland',          category: 'Sifatlar', level: 'A1' },
  { text: 'short',      translation: 'past',            category: 'Sifatlar', level: 'A1' },
  { text: 'long',       translation: 'uzun',            category: 'Sifatlar', level: 'A1' },
  { text: 'expensive',  translation: 'qimmat',          category: 'Sifatlar', level: 'A2' },
  { text: 'cheap',      translation: 'arzon',           category: 'Sifatlar', level: 'A2' },

  // ─── Transport ───
  { text: 'car',        translation: 'mashina',         category: 'Transport', level: 'A1' },
  { text: 'bus',        translation: 'avtobus',         category: 'Transport', level: 'A1' },
  { text: 'train',      translation: 'poyezd',          category: 'Transport', level: 'A1' },
  { text: 'plane',      translation: 'samolyot',        category: 'Transport', level: 'A1' },
  { text: 'bicycle',    translation: 'velosiped',       category: 'Transport', level: 'A2' },
  { text: 'taxi',       translation: 'taksi',           category: 'Transport', level: 'A1' },
  { text: 'boat',       translation: 'qayiq',           category: 'Transport', level: 'A2' },
  { text: 'ship',       translation: 'kema',            category: 'Transport', level: 'A2' },
  { text: 'truck',      translation: 'yuk mashinasi',   category: 'Transport', level: 'A2' },
  { text: 'motorcycle', translation: 'mototsikl',       category: 'Transport', level: 'B1' },

  // ─── Kiyim ───
  { text: 'shirt',      translation: 'ko\'ylak',        category: 'Kiyim', level: 'A1' },
  { text: 'pants',      translation: 'shim',            category: 'Kiyim', level: 'A1' },
  { text: 'dress',      translation: "ko'ylak (ayol)",  category: 'Kiyim', level: 'A2' },
  { text: 'shoes',      translation: 'tufli',           category: 'Kiyim', level: 'A1' },
  { text: 'hat',        translation: 'shapka',          category: 'Kiyim', level: 'A2' },
  { text: 'jacket',     translation: 'kurtka',          category: 'Kiyim', level: 'A2' },
  { text: 'coat',       translation: 'palto',           category: 'Kiyim', level: 'A2' },
  { text: 'socks',      translation: 'paypoq',          category: 'Kiyim', level: 'A2' },
  { text: 'glasses',    translation: "ko'zoynak",       category: 'Kiyim', level: 'A2' },
] as const
